# -*- coding: utf-8 -*-
"""Array and Creating routine.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BhBVdc4pgE-JJcP6HTItE20eyjGLnNgM
"""

import numpy as np

w=np.empty(6)

w

p=np.empty([3,2],dtype=int)

p

v=np.arange(2,21,2).reshape(5,2)

v

Q=np.zeros(6)

Q

R=np.zeros([6],dtype=int).reshape(3,2)

R

m=np.ones([4,5],dtype=int)

m

L=np.eye(1)

L

O=np.eye(1)

O

k=np.linspace(0,1,100)

k

n=np.linspace(10,20,5)

n

x=np.zeros((10,10))

x

x.shape[1]

Le=x.shape[1]

Le

for i in range(Le):
  x[1]=i

