# -*- coding: utf-8 -*-
"""Array Selection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1i9O-CqyN4HirDhqOjBmHWEReta6tjnvB
"""

import numpy as np

x=np.arange(1,11)

x

y=list(range(1,11))

y

x*4

y*4

x>5

mask=x>5

mask

x[mask]

a=np.array(['raj','ray','van','raj'])

a!='raj'

b=a!='raj'

a[b]

a[b]='ved'

a

a[b]='varun'

a