# -*- coding: utf-8 -*-
"""Copy of File handling and exeception.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G2bLVeU39ywLQKEyAsB_wfYG1dydTIQi
"""

file=open("/content/Rudra.txt","r")
content=file.read()
print(content)
file.close()

fw=open("/content/Rudra.txt","w")
content=fw.write("ok...so my name is also raj")
print(content)
fw.close()

fw=open("siddhant.txt","a")
content=fw.write("\n ok... so my name is also raj")
print(content)
fw.close()

#exception handling|

10/0

10/"a"

a=int(input("enter a no.:-"))
10/a

try:
  a=int(input("Enter a no.:-"))
  ok=10/a
  print(ok)

except  TypeError:
  print("bhai value sirf int hi daal")
except ZeroDivisionError:
  print("betta kuch to value deee")
else:
  print("krish ka gana jane ga")
finally:
  print("le....bette...")