# -*- coding: utf-8 -*-
"""matplotlib Bar.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NEyFSy6Wdyp1KQijWgp4tjWTvPAXIJP_
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import warnings
warnings.filterwarnings("ignore")

# Bar chat & Histogram
x,y=[2,4,6,8,3,1,],[67,32,76,34,40,95]

plt.bar(x,y,label="do something")
plt.xlabel("ids")
plt.ylabel("marks")
plt.xlim(0,10)
plt.ylim(0,100)

x=[2,4,6,8,10]
y=[22,44,33,55,67]
x1=[1,3,5,7,9]
y1=[33,66,21,34,67]

plt.bar(x,y,label="bar-1",color="blue")
plt.bar(x1,y1,label="bar-2",color="red")
plt.legend()

x,y=[2,4,6,8,3,1,],[67,32,76,34,40,95]

plt.bar(x,y,label="do something")
plt.xlabel("ids")
plt.ylabel("marks")
plt.xlim(0,10)
plt.ylim(0,100)

plt.xticks(rotation=45)
plt.yticks(rotation=120)
plt.grid(True)

age=[22,55,62,45,21,22,34,42,4,99,102,110,120,121.122,130,88,90,23]

ids=[x for x in range(len(age))]
#plt.bar(age,ids)
plt.bar(ids,age,label="age count",color="pink")
plt.legend
plt.title("janata")

#scatter plot
x=[1,2,3,4,5,6,7,8,9,10]
y=[2,4,5,4,3,2,5,7,9,7]

plt.scatter(x,y,label="do",marker="*",color="red",s=400)
plt.grid(True)

x=[1,2,3,4,5,6,7,8,9,10]
y=[2,4,5,4,3,2,5,7,9,7]

plt.scatter(x,y,label="do",marker="d",color="red",s=400)
plt.grid(True)

