# -*- coding: utf-8 -*-
"""Matplotlib line. python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAuQc9g3n2q9XXFrICpAcw5cuj9vquSP
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

#line plot
a=[2,4,6,8,10]
b=a
plt.plot(a,b)

x,y=[23,45,32,45,54],[45,78,22,11,55]
plt.plot(x,y)

a=[3,5,7,9,11]
b=a
plt.plot(a,b)

c=np.arange(0,10,0.1)
d=np.sin(c)

plt.plot(c,d)

b=np.arange(0,9,0.1)
d=np.cos(b)

plt.plot(b,d)

area=[600,800,1000,1200,1500]
price=[15,18,25,35,40]

plt.plot(area,price)
plt.title("siddhant shrivastav")
plt.xlabel("Quastech")
plt.ylabel("student")
plt.grid(True,color="green")

plt.plot([10,20,9,16],[23,45,56,100])
plt.show

#xlim and ylim to define x and y range
plt.plot(area,price,color="Black")

plt.title("Area vs Price")
plt.xlabel("Area in sq ft")
plt.ylabel("Price in lakh")

plt.xlim((100,2500))
plt.ylim((18,100))
plt.grid(True,color="red")

#xticks and yticks to rotate label
plt.plot(area,price,color="Black")

plt.title("Area vs Price")
plt.xlabel("Area in sq ft")
plt.ylabel("Price in lakh")

plt.xlim((100,2500))
plt.ylim((18,100))

plt.xticks(rotation=45)
plt.yticks(rotation=120)
plt.grid(True)

#multiple line plots

x=np.arange(1,20)
y1=np.sqrt(x)
y2=np.log(x)

plt.plot(x,y1,color="Blue")
plt.plot(x,y2,color="pink")
plt.grid(True,color="red")
plt.legend(labels=["s_r","long"])

