# -*- coding: utf-8 -*-
"""Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OdQJuabol2x7XzziDW_2k9t5mSBF4MJc
"""

import numpy as np

np.array([[1,2,3],[4,5,6]])

a=np.array([[1,2,3],[4,5,6]])

a.shape

a.size

a.reshape(3,2)

a.shape=(3,2)
a

a

a.T

np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

a.shape

a.size

a

a.T

x=np.arange(1,7)

x

x.shape

x=np.arange(1,7).reshape(2,3)

x

y=np.arange(7,13).reshape(2,3)

y

z=np.concatenate((x,y))
z

m=np.hstack((x,y))
m

Q=np.array([1,2,3,4,5,6])
np.vstack((Q))

ap=np.arange(1,7)
ap

ap=np.append(ap,[7,8,9])
ap

mn=np.array([2,3,4,5])

mn=np.insert(mn,0,1)
mn

mn=np.delete(mn,[0,2,3])
mn

mn

x=np.arange(1,7)

x

x[3]

x[4]

x[]

z=np.arange(1,21).reshape(5,4)

z

z[1]

z[0: :3]

x[2:5:1]

z[1:4:2,2: :1]

z[1: :4]

z[3:4]

z[3: :1]

z[4:9]

z[2: :-1,3: :-1]

z[4:1:-1,3:2:-1]

m=np.arange(1,7)

m

m[2]=55

m

m[: :2]=15

m

m[1::2]=0

m

N=np.arange(1,21).reshape(4,5)

N

N[: :4]=55
N

N[::1,3:4:1]=0.25

N