# -*- coding: utf-8 -*-
"""pandas panel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/172hsiQgOoWp44jmXcPgcFlRy2gozrGaT
"""

import numpy as np
import pandas as pd

import warnings
warnings.filterwarnings("ignore")

df=pd.read_table("course.csv",sep=",")

df

df.head(15)

df.tail(8)

a=pd.read_table("course.csv",sep=",")

a

col=["sr","city","institute","course","state","time"]

col

a=pd.read_table("course.csv",sep=",",header=None,names=col)

a

a.city

a

a.state.head()

a

a["state"]

a

a.city+" , "+a.state

a

a["city_state"]=a.city+" , "+a.state

a

a.city_state.head()

a.drop("city",axis=1)

a

a.drop("city",axis=1,inplace=True)

a

a.drop("state",axis=1,inplace=True)

a

a.drop(2,axis=0)

a

a.drop([3,4,5,6,7,8],axis=0)

a.set_index('sr',inplace=True)

a

a.drop(1,axis=0)

a.reset_index(inplace=True)

a

type(a)

a.shape

a.columns

a.describe(include=["object"])

ecom=pd.read_table("/content/Ecommerce Purchases",sep=",")
ecom

df.head(15)