# -*- coding: utf-8 -*-
"""Pandas series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DMQn6hosV2WTY-gyq6bBDHM9XxkmkrHY
"""

import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')

a=pd.Series()
print(a)

a=pd.Series(data=[1,2,3],index=["a","b","c"])
a

x={"a":1,"b":2,"c":3}
a = pd.Series(x)
a

x={"a":1,"b":2,"c":3}
a=pd.Series(data=x,index=["a","b","c","d"],dtype=int)
a

i=np.array(["a","b","c"])
d=np.array([1,2,3])
a=pd.Series(data=i,index=d)
a

t=pd.Series(data=5,index=[1,2,3,4,5,6])
t