# -*- coding: utf-8 -*-
"""Pandas.DataFrame.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14OlxKvp7H5-vcK3QH4t9Kj0HsJdA4_IZ
"""

import pandas as pd

d=pd.DataFrame()
d
print(d)

d=pd.DataFrame([1,2,3,4,5],columns=["sr_no"])
d

d=[['i','ii','iii'],['alpha','beta','gamma'],['a','b','c']]
a=pd.DataFrame(data=d,columns=["c1","c2","c3"])
a

name=['pratik','purvesh','faizan','sandesh','madhu','vinayak']
a=pd.DataFrame(name,columns=['name'])
a

'''
sep="," -> csv-: comma separated value:- name,age,python,ml,remark
sep="\t" -> tsv-: tab separated value:- name age python ml remark
sep="|" -> psv-: pipe separated value:- name|age|python|ml|remark
'''

df=pd.read_table("chiporders.tsv")
df

df.head(15)

df.tail(8)

df=pd.read_table("chiporders.tsv")
df

df.head(15)

df.tail(8)

df=pd.read_table("sales.csv",sep=",")
df

df.head(15)

df.tail(8)