# -*- coding: utf-8 -*-
"""project Bank.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jogjjGtBSjgI5QZNsKzGv3F446S5gKzi
"""

class user:
  def __init__(self,name,age,gender):
    self.name=name
    self.age=age
    self.gender=gender

  def showdetail(self):
    print("personal details:-")
    print(f"name:-{self.name.title()}")
    print(f"age:-{self.age}")
    print(f"gender:-{self.gender.title()}")

class bank(user):
  __balance=0
  __usercount=0
  def __init__(self,name,age,gender):
    super().__init__(name,age,gender)
    bank.__usercount+=1
    self.accountno=f"DenaBank00{bank.__usercount}"

  def ud(self):
    return self.__usercount

  def deposite(self,amount):
    self.amount=amount
    self.__balance+=self.amount
    print(f"account balance is updated:-rs.{self.__balance}")

  def withdraw(self,amount):
    self.amount=amount
    if(self.amount>self.__balance):
      print(f"insuffi amount,balance available:-rs. {self.__balance}")
    elif(100<=self.amount<=self.__balance):
      print("thank you for visiting")
      self.__balance -=self.amount
      print(f"current balance is :- rs {self.__balance}")
    else:
      print(f"you cannot withdraw less than 100 rs")

  def viewbalance(self):
     self.showdetail()
     print(f"ac no:-{self.accountno}")
     print(f"current balance is :-{self.__balance}")

  def transfer(self,username,amount):
     self.amount=amount
     if(self.amount>self.__balance):
       print(f"insuffi amount,balance available:- rs {self.__balance}")
     elif(1<=self.amount<=self.__balance):
       username.__balance+=self.amount
       self.__balance-=self.amount
       print("amount transfered successfully")
       print(f"current balance is :- rs {self.__balance} ")
     else:
       print("you cannot transfer less than 1 rs")

siddhant=bank("siddhant shrivastav",23,"male")
manoj=bank("manoj bhoir",34,"male")

siddhant.deposite(25000)

manoj.deposite(20000)

siddhant.withdraw(15000)