# -*- coding: utf-8 -*-
"""python basic to oops .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TG18tPXCtbqTCbw8zQIrIvx3lWx6bozh
"""

type(-2.4)
print(type(-2.4))

"can't"

print('''my name is raj \nyour name ram''')

'AE'

"/ bcd"

'''EF123'''

3+4j

3-4j

print(type((1,2,-1.1,"raj")))

a=-56
type(a)

a=123
type(a)

print('abc')

print(type([1,1.1,3+4j,(1,2,3)]))

print(type(123))

print(type(3+4j))

type((1,2,3,[1,5,3]))

print(type((1,2,3,[1,5,3])))

print(type('AE'))

{"a":100,"b":200,"c":300}

print(type({"a":100,"b":200,"c":300}))

{"a":100,"b":200,"a":300}

{1,2,3,4,5,6}
type({1,2,3,4,5,6})

print({1,2,3,4,5,6})

print(type({1,2,3,4,5,6}))

type(3+4j)

chr(2000)
chr(94)

print(id({1,2,3,4,3,2,3,2,3,1}))

a=10

print(a)

print(10)

print(type(10))

print(type(2.5))

print(type(3+7j))

print(type(" my name is raj /nyour name ram "))

print(type((1,2,-1.1,"raj")))

type((1,2,3,4,5))

print(type([1,1.1,3+4j,(1,2,3)]))

print(type({"a":100,"b":50,"c":100}))

print(type({"a":100,"b":200,"c":300}))

print(type({1,2,3,4,5,6}))

chr(2000)
chr(94)

print(id({1,2,3,4,5,6}))

a=78

print(a)

a=10

print(10)

a=123

_a=26

print(-a)

a==1

a#=1

a@=26

10="raj"

a_1="london"

a.b="ram"

x=10

print(x)

print(id(x))

y=20

print(y)

print(id(y))

x=x+y

y=x-y

x=x-y

print(x)

print(id(x))

print(y)

print(id(y))

x=10
print(x)
print(id(x))

y=20
print(y)
print(id(y))

x=x+y
y=x-y
x=x-y

print(x)
print(id(x))

print(y)
print(id(y))

m="ram"
print(m)
print(id(m))
n="raheem"
print(n)
print(id(n))

o=m
m=n
n=o

print(m)
print(id(m))
print(n)
print(id(n))

a='Raj'
b='kadam'
c=a+" "+b
print(c)

x=(1,2)
y=(3,4)
z=x+y
print(z)

Q=[1,2]
R=[3,4]
s=Q+R
print(s)

L={'a':1,'b':z}
M={'c':3,'d':4}
N = {}
N.update(L)
N.update(M)
print(N)

L='Raj'
M=(L+"")*3
print(M)

x=(1,'Raj')
y=x*3
print(y)

a=[1,3,5]
b=a*3
print(b)

c=(a+[4,5])*2
print(c)

x="i am siddhant"
y=x[3]+x[-2]
print(y)

R=(1,3,11,29,'Raj',53)
Q=R[3],R[4],R[2]
print(Q)

m=['Raj','team','soham']
n=m[1][0]+m[0][1]+m[1][2]+m[0][1]+m[2][4]
print(n)
n=list(n)
print(type(n))

a="my home is raj and i love python"
  b=a[-13:-7:1]+a[10:14:1]
  print(b)



c=a[0: :2]
print(c)

c=a[ : :-1]
print(c)

c=a[-7:6:-1]
print(c)

c=a[-7: :-1]
print(c)

x=(1,'R',2,'B',3,'K',4,'L')
y=x[2:6:1]
print(y)

z=x[-6:-2:1]
print(z)

R=x[-4:3:1]
print(R)

Q=x[-3:-6:-1]
print(Q)

x=(-1,1,-2,2,-3,3)
m=x[-1:-5:-1]
print(m)

m=[1,6,9,7,11,13,15,17]
L=m[-1:-6:-2]
print(L)

Q=m[6:1:-1]
print(Q)

Q=m[-1:-6:-1]
print(Q)

x=" i love siddhant "
print(x.upper())
print(x.lower())
print(x.capitalize())
#print(x.propar())

print(id(x))
o=x
x=x.upper
print(x)
print(id(x))
print(o)
print(o.title())
print(o.swapcase())
print(o.replace('siddhant','soham'))
print(o)

R="siddhant"
print(R.count('a'))

print(R.index('n'))

print(R.find('d'))

Q="----Raj----"
print(len(Q))
print(Q)
#Q.|strip()
Q.rstrip()
Q.strip()
Q.split()

m='Raj'
m.isalpha()
m.isnumeric()
m.istitle()
m.isupper()
m.islower()

a=[1,2,3,4]
  print(type(a))

  b=type(a)
  print(type(b))
  print(b)

  c=set(a)
  print(c)

a=[1,2,(1,2,3),{1,2,3}]
print(type(a))

a=(1,2,3,1,2,4)
print(a.count(1))
print(a.index(3))

x=[1,2,3]
print(type(x))
print(id(x))
x.append(4)
print(x)
print(id(x))
[1,2,3,4].append(5)
print(id([1,2,3,4,5]))

#x.append(5,6,7)
print(x)
#x.append[(5,6,7)]
print(x)
x.extend([5,6,7])
print(x)
print(id(x))

x.extend('raj')
print(x)
x.extend({1,2,5})
print(x)
x.extend({1,3,5})
print(x)
x.extend({'a','b',2})
print(x)
#x.insert(2,three)
print(2)

x=[1,2,3,4,5]
x.pop(4)
print(x)

x.remove(2)
print(x)

z=[6,9,5,3,2,4,3]
print(id(z))
z.sort()
print(z)
print(id(z))

y=[1,6,9,2]
y.reverse()
print(y)

m=[1,9,6,3,5,2]
m.sort(reverse=True)
print(m)

E={'mom':50,'dad':55,'sis':22,'me':20}
 E.keys()
 print(type(E.keys()))

 print(type(E.values()))


 E.get("dad")
 E.get("uncle","value no exist")

 E.get("mom","value no exist")
 E.get("uncle",51)

 E.update({'dad':54})
 print(E)
 print(id(E))
 E.update({'me':21})
 print(id(E))

 E. update({'uncle':50})

 f={'Aunty':44,'(-bro':1}
 E.update(f)
 print(E)
 print(id(E))

 E.setdefault('mam',35)
 print(E)
 print(id(E))

 E.keys()
 print(E)

 E.clear()
 print(E)

a={1,2,3,4}
b={3,4,5,6}
a.union(b)
a.difference(b)
a.intersection(b)
a.add(6)

a={1,2,3}
a.update([1,5,6])
a.update("raj")
a.update((111,222))
a.update({'a':1000,'b':900})
print(a)
a.remove('a')
a.discard('b')
print(a)
a.clear()
print(a)

a=10
b=5
print(a+b)
print(a-b)
print(a*b)
print(a%b)
print(a**b)
print(a//b)

a=10
b=20
z=30
print(a<b)
print(a>b)
print(a==b)
print(a!=b)
print(a<=b)
print(a>=b)
print(a>z<y)
print(a<b>z)

a=10
b=20
print((a>25) and (b<=20))
print((a<=b) and (a==b))
print((3-2) and (3-3))
print((3-2) or (3-3))
print((25-2) or (3-3))
print((a>b) and not(a<b))
print((2+3) and not(a>b))

a=(1,2,3)
print(z in a)
print(0 not in a)
print(6 in a)
print(6 not in a)
print((3-2) in a)

a=(1,2,3)
print(a is 1)
print(a is not 1)
print(a is (1,2,3))
print((1,2,3) is a)
print(a is b)

a=20
a=a*2
print(a)
a=a+5
print(a)
a=a-20
print(a)
a=a/2
print(a)
a=a//2
print(a)
a=a%2
print(a)

a=int(input("Enter a age:"))
if a>=18:
  print('yes')
else:
  print('No')

a=int(input("Enter a number:"))
if a==35 or a<=55:
  print('True')
else :
  print('False')

D=int(input("Enter a number:"))
if D % 2==0:
   print('it is visible')
else:
  print('it is not visible')

D=int(input("Enter a number:"))
if D % 2==0 or D % 11==0:
   print('it is visible')
else:
  print('it is visible')

a=int(input("Enter a number:"))
if a<2==0:
  if a%11==0:
     print('This is visible D')
  else:
     print('This is not visible D')
else:
  print('visible not D')

a=int(input("Enter a Number:-"))
b=str(input("Enter a Name:-"))
if b=='Raj':
   print(f"{a}+1=={a+1}")
else:
   print('Employee not found')

a=int(input("Enter a number:-"))
b=int(input("Enter a number:-"))
#sy=str(input("Enter a operation:-"))
if sy=='+':
   print(f"{a}+{b}=={a+b}")
elif sy=='-':
   print(f"{a}-{b}=={a-b}")
elif sy=='*':
   print(f"{a}*{b}=={a*b}")
elif sy=='/':
   print(f"{a}/{b}=={a/b}")
else:
   print("operand not found")

a=2
   b=3
   sum=a+b
   print("sum:",a+b)

l=20
b=30
a=l*b
print("area of rectangle:",a)

b=4
h=3
a=(b*h)/2
print("Area of a triangle:",a)

R=2
pi=3.14
a=2*pi*R
print("circumference of a circle:",a)

a=10
b=20
c=a*b
print("area of a square:",c)

a=int(input("Enter a number:"))
a=3
b=a*a*a
print("area of a cube:",b)

num=int(input("Enter a number:"))
num=4
print("The square root of number",num)

num=int(input("Enter a number:"))
num=4
print("The square of number:",num)

km=float(input("Enter the distance in kilometer:"))
meters=1000
print("The kilometer is equal to meters:",meters)

num=int(input("Enter a number:"))
last_digit=num%10
print("The last digit of {num} is: {last_digit}")

percentage=3
number=120
result=(percentage/100)*number
print("The percentage of number:",result)

m=10
print(m)
print(type(m))

n=12
print(n)
print(type(n))

m=m+n
n=m-n
m=m+n

print(m)
print(type(m))

print(n)
print(type(n))

num=float(input("Enter a number:"))
percentage=(num/100)*120
print(f"your percentage is:{percentage:.2f}%")

num=int(input("Enter a number:"))
if num % 2 == 0:
  print(f"{num} is even")
else:
  print(f"{num} is odd")

num1=float(input("Enter the first number:"))
num2=float(input("Enter the second number:"))
if num1>num2:
  print("num1 is greater than num2:")
elif num2>num1:
  print("num2 is greater than num1:")
else:
  print("num1 and num2 are equal")

num1=float(input("Enter the first number:"))
num2=float(input("Enter the second number:"))
num3=float(input("Enter the third number:"))
if num1>=num2 and num1>=num3:
  print("num1 is the greatest number")
elif num2>=num1 and num2>=num3:
  print("num2 is greatest number")
else:
  print("num3 is greatest number")

n=int(input("Enter a number:"))
if n%5==0:
  print("This is visible")
else:
  print("This is not visible")

n=int(input("Enter a number:"))
last_digit=n%10
if last_digit%2==0:
  print("The last digit of number divisible by 2")
else:
  print("The last digit of number divisible by not 2")

n=int(input("Enter a number:"))
if n%3==0 and n%9==0:
  print(f"{n} is divisible by 3 and 9")
else:
  print(f"{n} is not divisible by 3 and 9")

char=input("Enter a character:").lower()
if char is 'aeiou':
  print(f"{char} is a vowel")
else:
  print(f"{char} is not vowel")

string=input("Enter a string:").lower
if char is 'aeiou':
  print(f"{string} contain vowels")
else:
  print(f"{string} contain vowels")

age=int(input("Enter your age:"))
if age>=18:
  print("you are eligible for voting:")
else:
  print("you are not eligible for voting:")

age=int(input("Enter you age:"))
if age>60:
  print(f" At {age} year age,you are considered a senior citizen:")
else:
  print(f" At {age} year age,you are not considered a senior citizen:")

a=float(input("Enter a numbeer:"))
  if a<100 and a>=80:
     print('A+')
  elif a<80 and a>=70:
     print('A')
  elif a<70 and a>=60:
      print('B')
  elif a<60 and a>=50:
      print('c')
  elif a<50 and a>=35:
      print('D')
  elif a<35 and a>=1:
      print('Fail')
  else:
      print("marks and found")

a=int(input("Enter a salary:"))
if(a>=55000):
  bonus = a * 0.25
  print(f"bonus of 25%: {bonus:.2f}, total salary: {a + bonus:.2f}")
elif((a<50000) and (a>=40000)):
  bonus = a * 0.20
  print(f"bonus of 20%: {bonus:.2f}, total salary: {a + bonus:.2f}")
elif((a<40000) and (a>=30000)):
  bonus = a * 0.15
  print(f"bonus of 15%: {bonus:.2f}, total salary: {a + bonus:.2f}")
elif((a<30000) and (a>=15000)):
  bonus = a * 0.10
  print(f"bonus of 10%: {bonus:.2f}, total salary: {a + bonus:.2f}")
elif((a<15000) and (a>=8000)):
  bonus = a * 0.07
  print(f"bonus of 7%: {bonus:.2f}, total salary: {a + bonus:.2f}")
elif((a<8000) and (a>0)):
  bonus = a * 0.05 # Assuming 5% bonus for this range based on the structure
  print(f"bonus of 5%: {bonus:.2f}, total salary: {a + bonus:.2f}")
else:
  print("invalid salary")

a=int(input('Enter a Age:-'))
b=str(input('Enter a Country:-'))
if a>=18:
  if 'India'==b:
    print("eligible for vote")
  else:
    print("Don't have citizenship")
else:
  print("Age is less than 18 ")

a=float(input("Enter a number:"))

 if a>0:
  if a>8000:
    if a>15000:
      if a>3000:
        if a>40000:
          if a>50000:
            print('25%')
          else:
            print('20%')
        else:
          print('15%')
      else:
        print('10%')
    else:
      print('7%')
  else:
    print('5%')
else:
  print('invalid salary')

a=range(1,10)
 print(a)

 b=tuple(range(2,21,2))
 print(b)

# b=string(range(2,21,2))
 print(b)

b=set(range(2,21,2))
print(b)

 c=list(range(40,3,-4))
 print(c)

for i in range(1,11):
  print(i)
for i in range(1,11):
  print(i,end="")

a='raj'
for i in range(1,4):
  print(a)

x=2
for i in range(1,21,2):
  x+=2
  print(x)

a=5
for i in range(1,a):
  print(i)

a=1
for i in range(5,a,-1):
  print("*")

a=20
for i in range(a,1,-4):
    print("*")

a=100
for i in range(a,103,1):
  print("*",end=" ")

a=100
for i in range(a,103,a):
  print('*',end="")

a=4
for i in range(1,a):
  for j in range(1,a):
      print("*",end="")
  print()

a=4
for i in range(1,6):
  for j in range(1,6):
    print("*",end="")
  print()

a=4
for i in range(1,6):
  for j in range(0,j):
    print("*",end="")
  print()

n=5
for i in range(n,0,-1):
  for j in range(i):
    print("*",end="")
  print()

num=int(input("Enter a number:"))
fact=1
for i in range(1,num+1):
  fact=fact+1
print("factorial of",num,"is",fact)

a=int(input("Enter a year:"))
 if(a%4==0 and a%100==0)or a%400==0:
  print("leap Year")
 else:
  print("Not Leap,Year")

a=list(range(1990,2025))
LY=[]
NLY=[]
for i in a:
  if(i%4==0 and i%100==0) or i%400==0:
    LY.append(i)
  else:
    NLY.append(i)

print("LY")
print("NLY")

a=list(range(1990,2025))
LY=[]
NLY=[]
for i in a:
  if(i%4==0 and i%100!=0) or i%400==0:
    LY.append(i)
  else:
    NLY.append(i)

print(LY)
print(NLY)

a=5
for i in range(1,a+1):
  a+=9
  print(a)

a='Rajendra'
x=[]
for i in a:
  x.append(i)
print(x)

x=5
if x>3:
  print("yes")
else:
  print("No")

a=4
for i in range(1,4):
  for j in range(1,i+1):
    print("*",end="")
print()

a=5
for i in range(1,a):
  for j in range(i,a):
    print('*',end="")
  print()
for k in range(1,a):
  for L in range(1,k+1):
    print('*',end="")
  print()

a=5
for i in range(1,a):
  for j in range(i,a):
      print("*",end=" ")
  for K in range(1,i):
      print("+",end=" ")
  for L in range(1,i):
      print("+",end=" ")
  for M in range(i,a):
      print("*",end=" ")
  print()
for r in range(1,a):
  for s in range(1,r+1):
    print("*",end=" ")
  for t in range(r,a-1):
    print("+",end =" ")
  for u in range(r,a-1):
    print("+",end =" ")
  for s in range(1,r+1):
    print("*",end=" ")
  print()

n=5
for i in range(n,0,-1):
  for j in range(i):
    print("*",end="")
print()

rows=5
for i in range(1,rows+1):
  for j in range(1,i+1):
    print(j,end=" ")
  print()

rows=5
for i in range(1,rows+1):
  print(" "*(rows-1),end=" ")
  for j in range(1,i+1):
    print(j,end=" ")
  print()

for i in range(1,10):
  print(i)

a=10
for i in range(5):
  print("Hello")
  a+=1

a=4
for i in range(1,5):
  print(a)

a=10
for i in range(1,10):
  print("Hello,world")
  a+=1

name=input("Enter your name:")
for i in range(7):
  print(7)

for i in range(2,22,2):
  print(i)

for i in range(1,23,1):
  print(i)

fruits=['apple','banana','orange','cherry']
for fruit in fruits:
  print(fruit)

s='hello'
for char in s:
  print(char)

def check_vowel(s):
  vowel='aeiou'
  s=s.lower()
  for char in s:
    if char in vowel:
      return True
  return False

num=2
for i in range(1,11):
  print("{num}*{i}={num*1}")

sum_even=0
for i in range(1,11):
  if i%2==0:
    sum_even+=i
    print("sum of even number between 1 to 11:",sum_even)

sum_odd=1
for i in range(1,11):
  if i%3==0:
    sum_odd+=1
    print("sum of odd number between 1 to 11:",sum_odd)

n=input()
rev=' '
for char in n:
  rev=char+rev
if n==rev:
  print("yes,string is palindrome")
else:
  print("no,string is not palindrome")

for i in range(1,5):
  print(chr(65),end=" ")

for i in range(1,5):
    print(chr(64+i),end=" ")

for i in range(1,5):
  print(chr(67+i),end=" ")

a=5
for i in range(1,5):
  for j in range(1,i+1):
    print(chr(64+j),end=" ")
  print()

for k in range(1,5):
  for l in range(1,k+1):
    print(chr(67+l),end=" ")
  print()

a=1
  while a<=5:
    print(a,end=" ")
    a+=1

a=1
while a<5:
  for i in range(1,5):
    print(i,end=" ")
  print()
  a+=1

a=1
while a<5:
  for i in range(1,5):
    print(chr(64+i),end=" ")
  print()
  a+=1

a=1
while a<5:
  for i in range(1,5):
    print(chr(64+a),end=" ")
  print()
  a+=1

a=1
while a<5:
  for i in range(1,5):
    print(chr(64+j),end=" ")
  print()
  a+=1

a=1
while a<5:
  for i in range(1,a+1):
    print(chr(64+i),end=" ")
  print()
  a+=1

a=100
b=[]
while a>0:
 if a%2!=0:
  b.append(a)
 a-=1
print(b)
b.reverse()
print(b)

a=400
b=[]
while a>0:
  if a%2!=0 and a%11!=0:
    b.append(a)
  a-=1
  print(b)
  b.reverse()
  print(b)

a=1
while a<=5:
  for i in range(1,6,1):
    print('*')
  while a<=3:
    print('+')
    a+=1
  if a==4:
    print(2)
  else:
    print('3')
  print(a)
  a+=1
print(a+2)

a="1204"
if a[2]:
  print('X')
else:
  print('Y')

if len(list(a[0]+a[3])):
  print('q')
else:
  print('s')

if -5:
  print('i')
else:
  print('m')

n=1234
n1=n
rev=0
while n!=0:
  rem=n%10
  rev=(rev%10)+rem
  n=n/10
if n1==rev:
  print('it is a palindrome')
else:
  print('it is not a palindrome')

for i in range(1,a-18):
  for j in range(i,a-18):
    print("j",end="")
  print()

a=5
for i in range(1,a):
  for j in range(i,a):
    print("j",end="")
  print()

a=5
for i in range(1,a):
  for j in range(1,i+1):
    print("*",end="")
  print()

a=5
for i in range(a,1,-1):
  for j in range(1,i):
    print("*",end="")
  print()

a=1
while a<=4:
  print(chr(64+a),end="")
  a+=1

for i in range(1,5):
  for j in range(1,5):
    print(chr(64+j),end="")
  print()

a=1
while a<=4:
  b=1
  while b<=4:
    print(chr(64+b),end="")
    b+=1
  print()
  a+=1

(1,2,3,[1,5,3])

a=(1,2,3,4,5)
type(a)

a=[1,6,9,7]
b=tuple(a)
print(b)

sum(a)

min(a)

max(a)

a.count(6)

x=3
y=2
pow(x,y)

def greet():
  print("Hello World")

greet()

def Greet(n):
  print(f"Hello {n}")

Greet('siddhant')

def Greet():
  n=str(input('Enter a name:-'))
  print(f"hello {n}")

Greet()

def my_self(Name,Age):
  print(f'Hello---\n My Name is {Name} \n and Age is {Age}')

def addi(a,b):
  Add=a+b
  print(Add)

x=addi(100,110)
print(x)

def addi(a,b):
  Add=a+b
  return Add

x=addi(100,110)
print(x)

def sub(a,b):
  sub=a-b
  return sub

x=sub(100,110)
print(x)

def mul(a,b):
  mul=a*b
  return mul

x=mul(100,110)
print(x)

def prime(n):
  c=0
  for i in range(2,n):
    if n%i==0:
      print(f"{n} is not prime number")
      c+=1
      break

  if c==0:
    print(f"{n} is prime number")

prime(7)

def add(a,b):
  print(a,b)
add(22,20)

def siddhant(a,b=1500):
  print(a-b)
siddhant(8000)

def sidd(a=10,b=20):
  print(a+b)

sidd(50)
sidd()

def sidd(a,b=2,c=3):
  print(a+b+c)

sidd(10,20,30)

def add(a,b):
  print(a+b)

add(12,13)

def add(* item):
  return (list(item))
add(2,3,6,9,11)

lambda a,b:a+b

a=lambda a,b:a+b
a(12,13)

Aot=lambda b,h:0.5*b*h
Aot(17,7)

vos=lambda r:4/3*3.14*(r**3)
vos(25)

a=['Amey Aare','Vidya Yadav','Veer Pragragh','Samera Khan','Ram Round','Seema Dikshita']
a.sort(key=lambda name:name.lower().split()[-1])
print(a)

item=[{'saniya':20},{'soham':21},{'abdul':19},{'anas':22}]
print(type(item))

a={ }
print(type(a))

item=[{'saniya':20},{'soham':21},{'abdul':19},{'anas':22}]
def large_value(itemlist):
  """ to merge all dates in one dictionary"""
  d={}
  for i in itemlist:
      d.update(i)
  x=sorted(d.items(),key=lambda tup:tup[1])
  return x[-1]
a=large_value(item)
print(a)
help(large_value)

z={'a':1,'b':2,'c':3}
z.items()

m=[1,2,'R','',None,'','Raj',6,'',None]
filter(None,m)
a=list(filter(None,m))
print(a)

m=[1,6,9,7,9,11]
def vos(r):
  return 3/4 * 3.14 * (r**3)
map(vos,m)
a=set(map(vos,m))
print(a)

class Human:
    Eyes='Black'
    Nose='Sharp'
    weight=75
    Height=5.8
obj=Human()
obj.Nose

class Human:
   Eyes="Black"
   Nose="sharp"

   def walk(self):
      print("Human can walk")

   def speak(self):
      print("Human can speak")

per=Human()
per.Nose
per.walk()
per.speak()
per.Eyes

class Myclass():
  def Create_Name(self,Name):
     self.Name=Name

  def Display_Name(self):
     return self.Name

  def Great(self):
     return f"Hello {self.Name}"

per1=Myclass()
per1.Create_Name('Rajendra')
per1.Display_Name()
per1.Great()

class Myclass():
  def Create_Name(self,mayur):
     self.mayur=mayur

  def Display_Name(self):
     return self.mayur

  def Great(self):
     return f"Hello {self.mayur}"

per2=Myclass()
per2.Create_Name('siddhant')
per2.Display_Name()
per2.Great()

Name='Raj'
Age=26
class Entro():
   Name='siddhant'
   Age=27
   def Great(self):
      return f"my name is {Name} and my age is {Age}"
obj=Entro()
obj.Great()

class bonus:
  def Details(self,Name,Salary):
     self.Name=Name
     self.Salary=Salary

  def Calculate(self):
     self.Salary=self.Salary+(self.Salary/100*10)

  def Display(self):
     print(f"Name:-{self.Name} \n salary:-{self.Salary}")


s=bonus()
s.Details('Raj',25000)
s.Calculate()
s.Display()

class Mom():
   hair='Black'
   colour='White'
   Eyes='Brown'
   def Intro(self):
     return 'I am Mom'

class Dad():
   voice='harrish'
   height=51
   weight=75
   Eyes='Black'
   def Intro(self):
     return 'I am Dad'
class Dad():
   voice='harrish'
   height=51
   weight=75
   Eyes='Black'
   def Intro(self):
     return 'I am Dad'
class child(Mom,Dad):
     pass
c=child()
c.Eyes
c.voice
c.weight
c.Intro()

class Dad():
   voice='harrish'
   height=51
   weight=75
   Eyes='Black'
   def Intro(self):
     return 'I am Dad'

dad_obj = Dad()
print(dad_obj.Intro())
print(dad_obj.voice)

Name='Raj'
class Mom():
  Age=25
  def __init__(self,salary):
     self.salary=salary
     self.place='Theme'
m=Mom(2500)

class Employee:
  def __init__(self):
    self.name="siddhant"
    self.age=24

e1=Employee()
print("Name:{}".format(e1.name))
print("age:{}".format(e1.age))

class Abstr():
  a=10
  __b=20
  ___c=30

x=Abstr()
x.a

class Expencess():
  def __init__(self,sal1,sal2):
    self.__Husband=sal1
    self.__wife=sal2
    self.__Total_salary=self.__Husband+self.__wife

  def Income(self,Amount):
    self.__Total_salary+=Amount

  def Exp(self,Amount):
    self.__Total_salary-=Amount

  def Display_Total(self):
    return self.__Total_salary


s=Expencess(200,300)
s.Income(500)
s.Exp(100)
s.Display_Total()

class employee():
   empcount=0
   incat=1.10

   def __init__(self,first,last,salary):
     self.first=first
     self.last=last
     self.salary=salary
     self.email=first.lower()+"."+last.lower()+"@quastech.com"
     employee.empcount+=1
   def fullname(self):
     return f"{self.first.title()}  {self.last.title()}"
   def increment(self):
     self.salary - int(self.salary * employee.incat)

emp1=employee("siddhant","shrivastav",25000)
emp2=employee("snehal","shinde",22000)
emp3=employee("soham","malgunkar",34000)

emp1.email
emp1.first

emp1.fullname()

class Developer(employee):
  def __init__(self,first,last,salary,prog_lang):
    super().__init__(first,last,salary)
    self.prog_lang=prog_lang

dev1=Developer("abdul","shaikh",55000,"SQL")
dev2=Developer("siddhant","shrivastav",4500,"php")

dev2.empcount

dev2.email

dev1.first

class manager(employee):
  def __init__(self,first,last,salary,employees=None):
    super().__init__(first,last,salary)
    if(employees is None):
      self.employees=[]
    else:
      self.employees=employees
  def addemp(self,emp):
    if emp not in self.employees:
      self.employees.append(emp)
  def removemp(self,emp):
    if emp in self.employees:
      self.employees.remove(emp)
  def print_emps(self):
    for emp in self.employees:
      print("__>",emp.fullname())

class manager(employee):
  def __init__(self,first,last,salary,employees=None):
    super().__init__(first,last,salary)
    if(employees is None):
      self.employees=[]
    else:
      self.employees=employees
  def addemp(self,emp):
    if emp not in self.employees:
      self.employees.append(emp)
  def removemp(self,emp):
    if emp in self.employees:
      self.employees.remove(emp)
  def print_emps(self):
    for emp in self.employees:
      print("__>",emp.fullname())

mgr1=manager("siddhant","shrivastav",25000,[emp1,emp2,emp3])

mgr1.print_emps()

class mom():
  def Intro(self):
    return 'I love my son'

class child(mom):
  def Intro(self):
    super().Intro()
    return 'I love my mom'

x=child()
x.Intro()

class user:
  def __init__(self,name,age,gender):
    self.name=name
    self.age=age
    self.gender=gender

  def showdetail(self):
    print("personal details:-")
    print(f"name:-{self.name.title()}")
    print(f"age:-{self.age}")
    print(f"gender:-{self.gender.title()}")

s=user("siddhant",21,"male")
s.showdetail()

class user:
  def __init__(self,name,age,gender):
    self.name=name
    self.age=age
    self.gender=gender

  def showdetail(self):
    print("personal details:-")
    print(f"name:-{self.name.title()}")
    print(f"age:-{self.age}")
    print(f"gender:-{self.gender.title()}")

class bank(user):
  __balance=0
  __usercount=0
  def __init__(self,name,age,gender):
    super().__init__(name,age,gender)
    bank.__usercount+=1
    self.accountno=f"DenaBank00{bank.__usercount}"

  def ud(self):
    return self.__usercount

  def deposite(self,amount):
    self.amount=amount
    self.__balance+=self.amount
    print(f"account balance is updated:-rs.{self.__balance}")

  def withdraw(self,amount):
    self.amount=amount
    if(self.amount>self.__balance):
      print(f"insuffi amount,balance available:-rs. {self.__balance}")
    elif(100<=self.amount<=self.__balance):
      print("thank you for visiting")
      self.__balance -=self.amount
      print(f"current balance is :- rs {self.__balance}")
    else:
      print(f"you cannot withdraw less than 100 rs")

  def viewbalance(self):
     self.showdetail()
     print(f"ac no:-{self.accountno}")
     print(f"current balance is :-{self.__balance}")

  def transfer(self,username,amount):
     self.amount=amount
     if(self.amount>self.__balance):
       print(f"insuffi amount,balance available:- rs {self.__balance}")
     elif(1<=self.amount<=self.__balance):
       username.__balance+=self.amount
       self.__balance-=self.amount
       print("amount transfered successfully")
       print(f"current balance is :- rs {self.__balance} ")
     else:
       print("you cannot transfer less than 1 rs")

siddhant=bank("siddhant shrivastav",23,"male")
manoj=bank("manoj bhoir",34,"male")

siddhant.deposite(25000)

manoj.deposite(20000)

siddhant.withdraw(15000)

x="siddhant"
x.isalpha