# -*- coding: utf-8 -*-
"""Seaborn python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eaHaZycfdErvWAUZYEkxIZKKUL1k52-A
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/Automobile_data.csv",sep=",")
df

x=np.arange(10)
y=np.sqrt(x)

sns.lineplot(y)

sns.scatterplot(y)

sns.barplot(y)

sns.histplot(df["price"])

width=df['width'].mean()
dwidth=df['width'].median()

sns.displot(df['width'])
plt.axvline(width,color="pink")
plt.axvline(width,color="black")
plt.grid(True)

sns.countplot(data=df,x="body-style")

plt.figure(figsize=(8,8))

sns.countplot(data=df,y="make")

sns.countplot(data=df,y="body-style",hue="fuel-type")